"""Central configuration. Everything overridable via env so leaderboard A/B needs no code edits."""
import os

def _flag(name: str, default: str) -> bool:
    return os.environ.get(name, default).strip().lower() in ("1", "true", "yes", "on")

# --- Secrets ---
# Track 2 harness injects NO env keys (Participant Guide: "use your own credentials
# inside the container") → fall back to build-time-embedded creds when env is empty.
# Env vars still win when present (local dev, Track-1-style harnesses).
try:
    from ._creds import EMBEDDED  # generated by gen_creds.py at build; gitignored
except ImportError:
    EMBEDDED = {}


def _secret(name: str) -> str:
    v = os.environ.get(name, "").strip()
    if not v and name in EMBEDDED:
        import base64 as _b64
        try:
            v = _b64.b64decode(EMBEDDED[name]).decode().strip()
        except Exception:
            v = ""
    return v


FIREWORKS_API_KEY = _secret("FIREWORKS_API_KEY")
GEMINI_API_KEY = _secret("GEMINI_API_KEY")
# Optional second/third Gemini project keys: independent quota pools + serial Gemma lanes
GEMINI_API_KEY_2 = _secret("GEMINI_API_KEY_2")
GEMINI_API_KEY_3 = _secret("GEMINI_API_KEY_3")
# Optional OpenRouter key: google/gemma-4-31b-it:free = same Gemma, independent capacity pool
OPENROUTER_API_KEY = _secret("OPENROUTER_API_KEY")

# --- Endpoints ---
FIREWORKS_BASE = "https://api.fireworks.ai/inference/v1"
GEMINI_OPENAI_BASE = "https://generativelanguage.googleapis.com/v1beta/openai"
OPENROUTER_BASE = "https://openrouter.ai/api/v1"
GEMMA_OPENROUTER_MODEL = os.environ.get("GEMMA_OPENROUTER_MODEL", "google/gemma-4-31b-it:free")
# When more providers exist in the chain, the primary Gemini attempt is capped so a
# congested-window hang (36s+ measured) leaves time for the next Gemma pool.
GEMMA_PRIMARY_CAP = float(os.environ.get("GEMMA_PRIMARY_CAP", "20"))

# --- Models (verified live 2026-07-08; see STATUS.md) ---
VISION_MODEL = os.environ.get("VISION_MODEL", "accounts/fireworks/models/kimi-k2p6")
VISION_MODEL_FALLBACK = os.environ.get("VISION_MODEL_FALLBACK", "accounts/fireworks/models/kimi-k2p5")
GEMMA_MODEL = os.environ.get("GEMMA_MODEL", "gemma-4-31b-it")
# gemma-4-26b-a4b-it 500'd on every live probe 2026-07-08 — disabled by default;
# re-enable via env if it recovers. Empty string = no second Gemma model in the chain.
GEMMA_MODEL_FALLBACK = os.environ.get("GEMMA_MODEL_FALLBACK", "")
AUDIO_MODEL = os.environ.get("AUDIO_MODEL", "gemini-2.5-flash")  # Fireworks audio deprecated 2026-06-10
# Third styling candidate + verifier on the Gemini flash family (free tier, separate
# quota from Gemma, strong native vision). ENABLE_FLASH_STYLE=0 turns the lane off.
# Model availability DIFFERS BY ACCOUNT (older projects: 2.5-flash; newer: 3.x family
# where 2.5 is retired) → calls walk a (model, key) chain, first success wins.
FLASH_STYLE_MODEL = os.environ.get("FLASH_STYLE_MODEL", "gemini-2.5-flash")
ENABLE_FLASH_STYLE = _flag("ENABLE_FLASH_STYLE", "1")
FLASH_STYLE_FRAMES = int(os.environ.get("FLASH_STYLE_FRAMES", "8"))


def flash_style_chain():
    """(model, key) attempts for flash styling/verification, best-first.
    gemini-3.1-flash-lite (new accounts): 1.3s, correct motion reading (probed);
    gemini-2.5-flash (older accounts): proven, 4s."""
    chain = []
    if GEMINI_API_KEY_2:
        chain += [("gemini-3.1-flash-lite", GEMINI_API_KEY_2)]
    if GEMINI_API_KEY_3:
        # callable on older-catalog accounts even when unlisted (probed)
        chain += [("gemini-3.1-flash-lite", GEMINI_API_KEY_3)]
    if GEMINI_API_KEY:
        chain += [(FLASH_STYLE_MODEL, GEMINI_API_KEY)]
    if GEMINI_API_KEY_3:
        chain += [("gemini-2.5-flash", GEMINI_API_KEY_3)]
    return chain


def flash_preview_chain():
    """Full-size gen-3 flash: stronger captions, flakier availability (503/timeouts).
    Runs as a SEPARATE parallel candidate so failures cost nothing."""
    chain = []
    if GEMINI_API_KEY_3:
        chain += [("gemini-3-flash-preview", GEMINI_API_KEY_3)]
    if GEMINI_API_KEY_2:
        chain += [("gemini-3-flash-preview", GEMINI_API_KEY_2)]
    return chain


# Measured Jul 10: preview lane DROPPED verify coverage 15/15 -> 6/15 (503-flaky
# model + doubled RPM pressure) and gained nothing. Off by default; env-flippable.
ENABLE_FLASH_PREVIEW = _flag("ENABLE_FLASH_PREVIEW", "0")


def audio_chain():
    """(model, key) attempts for audio transcription (input_audio support proven on
    2.5-flash; 3.1-flash-lite is multimodal on the newer account)."""
    chain = []
    if GEMINI_API_KEY:
        chain += [(AUDIO_MODEL, GEMINI_API_KEY)]
    if GEMINI_API_KEY_3:
        chain += [("gemini-2.5-flash", GEMINI_API_KEY_3)]
    if GEMINI_API_KEY_2:
        chain += [("gemini-3.1-flash-lite", GEMINI_API_KEY_2)]
    return chain
# Last-resort styling fallback if Gemini API is entirely down (weakens Gemma story; logged loudly)
TEXT_FALLBACK_MODEL = os.environ.get("TEXT_FALLBACK_MODEL", "accounts/fireworks/models/kimi-k2p6")

# --- Contract paths ---
INPUT_PATH = os.environ.get("INPUT_PATH", "/input/tasks.json")
OUTPUT_PATH = os.environ.get("OUTPUT_PATH", "/output/results.json")
WORK_DIR = os.environ.get("WORK_DIR", "/tmp/clips")

# --- Styles contract ---
ALL_STYLES = ["formal", "sarcastic", "humorous_tech", "humorous_non_tech"]

# --- Feature flags (baseline ships conservative; Stage B flips via env, no code change) ---
ENABLE_AUDIO = _flag("ENABLE_AUDIO", "1")     # gemini-2.5-flash transcription (separate quota from Gemma)
# OCR default OFF in the speed-first envelope: RapidOCR on a weak eval CPU can eat
# seconds we no longer have; Kimi reads on-screen text from frames anyway.
ENABLE_OCR = _flag("ENABLE_OCR", "0")
BEST_OF_N = int(os.environ.get("BEST_OF_N", "1"))          # 1 = banked baseline; 3 = Stage B
ENABLE_JUDGE = _flag("ENABLE_JUDGE", "0")     # Gemma judge-replica rerank (only meaningful if N>1)
ENABLE_CRITIQUE = _flag("ENABLE_CRITIQUE", "0")  # Gemma self-critique/repair pass

# --- Frames ---
# SPEED-FIRST: leaderboard evidence (v1@27s-deadline=0.61 vs v6@55s-deadline=0.45 with
# strictly better captions) says clips finishing over ~30s DON'T COUNT — the judge sees
# the pre-fill. Every budget below is sized so a clip lands in ~15-22s worst-case ~27s.
MAX_FRAMES = int(os.environ.get("MAX_FRAMES", "8"))
MIN_FRAMES = int(os.environ.get("MIN_FRAMES", "6"))
FRAME_LONG_EDGE = int(os.environ.get("FRAME_LONG_EDGE", "768"))
FRAME_JPEG_Q = int(os.environ.get("FRAME_JPEG_Q", "5"))  # ffmpeg -q:v scale (2..6; lower=better)

# --- Concurrency & budgets (seconds) ---
GLOBAL_BUDGET = float(os.environ.get("GLOBAL_BUDGET", "540"))
CLIP_CONCURRENCY = int(os.environ.get("CLIP_CONCURRENCY", "3"))  # CPU-starved runners
# Gemini free tier 500s on ANY concurrent Gemma calls (verified live) → serialize + gap
GEMMA_CONCURRENCY = int(os.environ.get("GEMMA_CONCURRENCY", "1"))
GEMMA_MIN_GAP = float(os.environ.get("GEMMA_MIN_GAP", "0.8"))
# Small stagger keeps the serial Gemma lane fed without pushing clips past the
# per-request window. run() shrinks it further for large task counts.
CLIP_STAGGER = float(os.environ.get("CLIP_STAGGER", "8"))
CLIP_DEADLINE = float(os.environ.get("CLIP_DEADLINE", "25"))
# Tight: on timeout the pipeline STREAMS frames from the URL instead (ranged reads),
# which beats waiting on a 90MB file over a slow pipe.
DOWNLOAD_TIMEOUT = float(os.environ.get("DOWNLOAD_TIMEOUT", "8"))
GROUNDING_TIMEOUT = float(os.environ.get("GROUNDING_TIMEOUT", "7"))
AUDIO_TIMEOUT = float(os.environ.get("AUDIO_TIMEOUT", "8"))
AUDIO_MAX_SEC = float(os.environ.get("AUDIO_MAX_SEC", "90"))
# Gemma races the banked Kimi result; calm-window Gemma is 7-11s so a ~12s grace
# fits inside the 25s deadline. Congested windows: Kimi ships (honest logs).
STYLE_GRACE = float(os.environ.get("STYLE_GRACE", "12"))
KIMI_STYLE_TIMEOUT = float(os.environ.get("KIMI_STYLE_TIMEOUT", "8"))
# Kimi styles multimodally (sees keyframes + facts-hint) → self-corrects grounding errors.
KIMI_STYLE_FRAMES = int(os.environ.get("KIMI_STYLE_FRAMES", "6"))
BACKUP_RESERVE = float(os.environ.get("BACKUP_RESERVE", "9"))     # time reserved for the Kimi lane
GEMMA_MIN_GRACE = float(os.environ.get("GEMMA_MIN_GRACE", "5"))   # below this, don't even try Gemma
JUDGE_TIMEOUT = float(os.environ.get("JUDGE_TIMEOUT", "8"))
CRITIQUE_TIMEOUT = float(os.environ.get("CRITIQUE_TIMEOUT", "8"))

# --- Gemma decoding ---
GEMMA_MAX_TOKENS = int(os.environ.get("GEMMA_MAX_TOKENS", "2600"))  # directed thinking ~150 + answer; cap doubles as runaway-thought guard
# Attach keyframes to the Gemma styling call (gemma-4-31b is multimodal — verified).
# Frames ALWAYS ride along when grounding failed (facts empty — rescue mode).
# GEMMA_VISION=1 additionally sends frames alongside good facts, but a 3-image call
# measured ~30s on the free tier vs ~10s text-only — it clogs the serial lane, so
# default OFF; facts carry the visual grounding on the fast path.
GEMMA_VISION = _flag("GEMMA_VISION", "0")
GEMMA_VISION_FRAMES = int(os.environ.get("GEMMA_VISION_FRAMES", "3"))
GEMMA_TEMP_GEN = float(os.environ.get("GEMMA_TEMP_GEN", "0.9"))
GEMMA_TEMP_JUDGE = float(os.environ.get("GEMMA_TEMP_JUDGE", "0.0"))

# Caption length band (verbosity-bias defense; RESEARCH.md §6)
WORD_MIN = int(os.environ.get("WORD_MIN", "20"))
WORD_MAX = int(os.environ.get("WORD_MAX", "45"))
